[project]
name = "atsphinx-bulma"
version = "0.3.0"
description = "Bluma using suite for Sphinx."
authors = [{name = "Kazuya Takei", email = "myself@attakei.net"}]
license = "Apache-2.0"
requires-python = ">= 3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Sphinx",
    "Framework :: Sphinx :: Extension",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Documentation",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing",
    "Topic :: Text Processing :: Markup",
    "Topic :: Text Processing :: Markup :: reStructuredText",
]
readme = "README.rst"
dependencies = [
    "beautifulsoup4>=4",
    "sphinx>=7.3.0",
    "typing-extensions>=4.12.2",
]

[project.entry-points."sphinx.html_themes"]
bulma-basic = "atsphinx.bulma.themes.bulma_basic"

[project.urls]
Home = "https://github.com/atsphinx/bulma"
Documentation = "https://atsphinx.github.io/bulma"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "docs" },
    "esbonio",
    "sphinx-autobuild",
]
lint = [
    "mypy>=1.13.0",
    "types-beautifulsoup4>=4.12.0.20250516",
    "types-docutils>=0.21.0.20241128",
]
test = [
    "pytest",
]
docs = [
    "atsphinx-goto-top>=0.1.1",
    "atsphinx-mini18n",
    "sphinx-intl",
    "sphinx-toolbox>=3.8.1",
]

[tool.uv]
managed = true

[tool.ruff.lint]
select = ["C90", "D", "E", "F", "I", "W"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/atsphinx"]
only-includes = ["src/atsphinx"]

[tool.mypy]
python_version = "3.9"

[[tool.mypy.overrides]]
module = ["atsphinx.bulma.*"]
ignore_missing_imports = true
