[theme]
inherit = "basic"
stylesheets = ["style.css"]
sidebars = [
    "sidebar/logo.html",
    "sidebar/searchbox.html",
    "sidebar/localtoc.html",
    "sidebar/relations.html",
    "sidebar/sourcelink.html",
]

[options]
bulma_version = "1.0.2"
bulmaswatch = ""
logo_class = "is-128x128"
logo_description = ""
color_mode = ""
sidebar_position = "left"
sidebar_size = 2
navbar_icons = []
show_theme_credit = true
