---
name: "Setup aqua using cache."

inputs:
  aqua_config_path:
    description: "Relative path of aqua configuration file for repository root"
    required: false
    default: "./aqua.yaml"
  aqua_version:
    description: "Using aqua version"
    required: false
    default: "v2.55.0"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: "~/.local/share/aquaproj-aqua"
        key: "v2-aqua-installer-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(inputs.aqua_config_path) }}"
        restore-keys: |
          v2-aqua-installer-${{runner.os}}-${{runner.arch}}-
    - uses: "aquaproj/aqua-installer@0d9bbff5b5efc37244b8271be7e59cb25fbc8366"
      with:
        aqua_version: "${{ inputs.aqua_version }}"
      env:
        AQUA_CONFIG: "${{ inputs.aqua_config_path }}"
