---
name: "Setup aqua using cache."

inputs:
  aqua_config_path:
    description: "Relative path of aqua configuration file for repository root"
    required: false
    default: "./aqua.yaml"
  aqua_version:
    description: "Using aqua version"
    required: false
    default: "v2.55.0"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: "~/.local/share/aquaproj-aqua"
        key: "v2-aqua-installer-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(inputs.aqua_config_path) }}"
        restore-keys: |
          v2-aqua-installer-${{runner.os}}-${{runner.arch}}-
    - uses: "aquaproj/aqua-installer@7053e18161e62dffa977457ced6cd24d6c3dda24"
      with:
        aqua_version: "${{ inputs.aqua_version }}"
      env:
        AQUA_CONFIG: "${{ inputs.aqua_config_path }}"
