---
name: "Setup aqua using cache."

inputs:
  aqua_config_path:
    description: "Relative path of aqua configuration file for repository root"
    required: false
    default: "./aqua.yaml"
  aqua_version:
    description: "Using aqua version"
    required: false
    default: "v2.55.0"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: "~/.local/share/aquaproj-aqua"
        key: "v2-aqua-installer-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(inputs.aqua_config_path) }}"
        restore-keys: |
          v2-aqua-installer-${{runner.os}}-${{runner.arch}}-
    - uses: "aquaproj/aqua-installer@751097a5968c57d115b51fbab1febb17a5b2010f"
      with:
        aqua_version: "${{ inputs.aqua_version }}"
      env:
        AQUA_CONFIG: "${{ inputs.aqua_config_path }}"
